/*-----------------------------------------------------------------------------------------*/
  -- Database Objects for the Customer Sizing V1.2 Streamlit App
  -- Customer_Sizing_V1.2.sql
  -- Repo: https://github.com/sfc-gh-sdickson/Customer-Sizing
  -- 11-Jun-2025 Author: Stephen Dickson
  -- Stephen.Dickson@Snowflake.com
/*-----------------------------------------------------------------------------------------*/


create or replace DATABASE SIZING_TOOL;
create or replace SCHEMA CUSTOMER_SIZING;
use SCHEMA SIZING_TOOL.CUSTOMER_SIZING;

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.ANALYTICS_WORKLOADS (
	SIZING_ID VARCHAR(50),
	ANALYTICS_INDEX NUMBER(38,0),
	WORKLOAD_NAME VARCHAR(255),
	PRIMARY_TOOL VARCHAR(100),
	HOURS_PER_DAY NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	QUERIES_PER_DAY NUMBER(38,0),
	BASIC_USERS_PCT NUMBER(38,0),
	EXPERT_USERS_PCT NUMBER(38,0),
	POWER_USERS_PCT NUMBER(38,0),
	PEAK_DAYS NUMBER(38,0),
	PEAKS_PER_DAY NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CONCURRENT_QUERIES NUMBER(38,0),
	CACHING_PCT NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.DATA_SOURCES (
	SIZING_ID VARCHAR(50),
	SOURCE_INDEX NUMBER(38,0),
	SOURCE_NAME VARCHAR(255),
	SOURCE_TYPE VARCHAR(100),
	CURRENT_VOLUME_TB FLOAT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.OTHER_WORKLOADS (
	SIZING_ID VARCHAR(50),
	OTHER_INDEX NUMBER(38,0),
	WORKLOAD_NAME VARCHAR(255),
	WORKLOAD_TYPE VARCHAR(100),
	HOURS_PER_DAY NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	QUERIES_PER_DAY NUMBER(38,0),
	DATA_VOLUME_GB FLOAT,
	PEAK_DAYS NUMBER(38,0),
	PEAKS_PER_DAY NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CONCURRENT_QUERIES NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.OTHER_WORKLOADS (
	SIZING_ID VARCHAR(50),
	OTHER_INDEX NUMBER(38,0),
	WORKLOAD_NAME VARCHAR(255),
	WORKLOAD_TYPE VARCHAR(100),
	HOURS_PER_DAY NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	QUERIES_PER_DAY NUMBER(38,0),
	DATA_VOLUME_GB FLOAT,
	PEAK_DAYS NUMBER(38,0),
	PEAKS_PER_DAY NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CONCURRENT_QUERIES NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.PIPELINES (
	SIZING_ID VARCHAR(50),
	PIPELINE_INDEX NUMBER(38,0),
	PIPELINE_NAME VARCHAR(255),
	FREQUENCY VARCHAR(100),
	JOBS_PER_DAY NUMBER(38,0),
	VOLUME_PER_JOB_GB FLOAT,
	RUNTIME_MINUTES NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	CONCURRENT_JOBS NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.SIZING_MAIN (
	SIZING_ID VARCHAR(50) NOT NULL,
	CUSTOMER_NAME VARCHAR(255),
	INDUSTRY VARCHAR(100),
	CONTACT_NAME VARCHAR(255),
	CONTACT_EMAIL VARCHAR(255),
	COMPANY_SIZE VARCHAR(100),
	EXISTING_DATA_PLATFORM VARCHAR(255),
	BUSINESS_OWNER VARCHAR(255),
	TECH_OWNER VARCHAR(255),
	DEV_START_DATE DATE,
	GO_LIVE_DATE DATE,
	SUCCESS_METRICS VARCHAR(16777216),
	ROADBLOCKS VARCHAR(16777216),
	RAMP_UP_CURVE VARCHAR(50),
	DATA_SOURCES_COUNT NUMBER(38,0),
	INITIAL_RAW_VOLUME_TB FLOAT,
	FINAL_RAW_VOLUME_TB FLOAT,
	TOOLS VARCHAR(255),
	DATA_RETENTION_PERIOD NUMBER(38,0),
	DATA_SENSITIVITY VARCHAR(50),
	EXPECTED_WAREHOUSES NUMBER(38,0),
	TOTAL_USERS NUMBER(38,0),
	QUERY_COMPLEXITY VARCHAR(50),
	HAS_OTHER_WORKLOADS VARCHAR(10),
	GEOGRAPHIC_DISTRIBUTION VARCHAR(255),
	HIGH_AVAILABILITY_REQUIREMENTS VARCHAR(50),
	DISASTER_RECOVERY_REQUIREMENTS VARCHAR(50),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (SIZING_ID)
);
