/*-----------------------------------------------------------------------------------------*/
  -- Database Objects for the Customer Sizing V1.4 Streamlit App  
  -- Customer_Sizing_V1.4.sql
  -- Repo: https://github.com/sfc-gh-sdickson/Customer-Sizing
  -- Enhanced with Use Cases functionality
  -- Author: Stephen Dickson  
  -- Stephen.Dickson@Snowflake.com
/*-----------------------------------------------------------------------------------------*/

create or replace DATABASE SIZING_TOOL;
create or replace SCHEMA CUSTOMER_SIZING;
use SCHEMA SIZING_TOOL.CUSTOMER_SIZING;

-- New Use Cases table for hierarchical grouping
create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.USE_CASES (
	SIZING_ID VARCHAR(50),
	USE_CASE_ID VARCHAR(50) NOT NULL,
	USE_CASE_NAME VARCHAR(255) NOT NULL,
	USE_CASE_DESCRIPTION VARCHAR(16777216),
	PARENT_USE_CASE_ID VARCHAR(50), -- For hierarchical structure
	BUSINESS_PRIORITY VARCHAR(50), -- High, Medium, Low
	EXPECTED_TIMELINE VARCHAR(100), -- When this use case will be implemented
	BUSINESS_OWNER VARCHAR(255),
	TECHNICAL_OWNER VARCHAR(255),
	SUCCESS_METRICS VARCHAR(16777216),
	ESTIMATED_USERS NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (USE_CASE_ID),
	FOREIGN KEY (SIZING_ID) REFERENCES SIZING_TOOL.CUSTOMER_SIZING.SIZING_MAIN(SIZING_ID)
);

-- Enhanced Analytics Workloads table with use case association
create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.ANALYTICS_WORKLOADS (
	SIZING_ID VARCHAR(50),
	ANALYTICS_INDEX NUMBER(38,0),
	USE_CASE_ID VARCHAR(50), -- New foreign key to use cases
	WORKLOAD_NAME VARCHAR(255),
	PRIMARY_TOOL VARCHAR(100),
	HOURS_PER_DAY NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	QUERIES_PER_DAY NUMBER(38,0),
	BASIC_USERS_PCT NUMBER(38,0),
	EXPERT_USERS_PCT NUMBER(38,0),
	POWER_USERS_PCT NUMBER(38,0),
	PEAK_DAYS NUMBER(38,0),
	PEAKS_PER_DAY NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CONCURRENT_QUERIES NUMBER(38,0),
	CACHING_PCT NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (USE_CASE_ID) REFERENCES SIZING_TOOL.CUSTOMER_SIZING.USE_CASES(USE_CASE_ID)
);

-- Enhanced Data Sources table with use case association
create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.DATA_SOURCES (
	SIZING_ID VARCHAR(50),
	SOURCE_INDEX NUMBER(38,0),
	USE_CASE_ID VARCHAR(50), -- New foreign key to use cases
	SOURCE_NAME VARCHAR(255),
	SOURCE_TYPE VARCHAR(100),
	CURRENT_VOLUME_TB FLOAT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (USE_CASE_ID) REFERENCES SIZING_TOOL.CUSTOMER_SIZING.USE_CASES(USE_CASE_ID)
);

-- Enhanced Other Workloads table with use case association
create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.OTHER_WORKLOADS (
	SIZING_ID VARCHAR(50),
	OTHER_INDEX NUMBER(38,0),
	USE_CASE_ID VARCHAR(50), -- New foreign key to use cases
	WORKLOAD_NAME VARCHAR(255),
	WORKLOAD_TYPE VARCHAR(100),
	HOURS_PER_DAY NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	QUERIES_PER_DAY NUMBER(38,0),
	DATA_VOLUME_GB FLOAT,
	PEAK_DAYS NUMBER(38,0),
	PEAKS_PER_DAY NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CONCURRENT_QUERIES NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (USE_CASE_ID) REFERENCES SIZING_TOOL.CUSTOMER_SIZING.USE_CASES(USE_CASE_ID)
);

-- Enhanced Pipelines table with use case association
create or replace TABLE SIZING_TOOL.CUSTOMER_SIZING.PIPELINES (
	SIZING_ID VARCHAR(50),
	PIPELINE_INDEX NUMBER(38,0),
	USE_CASE_ID VARCHAR(50), -- New foreign key to use cases
	PIPELINE_NAME VARCHAR(255),
	FREQUENCY VARCHAR(100),
	JOBS_PER_DAY NUMBER(38,0),
	VOLUME_PER_JOB_GB FLOAT,
	RUNTIME_MINUTES NUMBER(38,0),
	DAYS_PER_MONTH NUMBER(38,0),
	CONCURRENT_JOBS NUMBER(38,0),
	PEAK_DURATION_MINUTES NUMBER(38,0),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	FOREIGN KEY (USE_CASE_ID) REFERENCES SIZING_TOOL.CUSTOMER_SIZING.USE_CASES(USE_CASE_ID)
);

-- Enhanced Sizing Main table (unchanged for now, but could include default use case info)
CREATE OR REPLACE TABLE SIZING_TOOL.CUSTOMER_SIZING.SIZING_MAIN (
	SIZING_ID VARCHAR(50) NOT NULL,
	CUSTOMER_NAME VARCHAR(255),
	INDUSTRY VARCHAR(100),
	CONTACT_NAME VARCHAR(255),
	CONTACT_EMAIL VARCHAR(255),
	COMPANY_SIZE VARCHAR(100),
	EXISTING_DATA_PLATFORM VARCHAR(255),
	BUSINESS_OWNER VARCHAR(255),
	TECH_OWNER VARCHAR(255),
	DEV_START_DATE DATE,
	GO_LIVE_DATE DATE,
	SUCCESS_METRICS VARCHAR(16777216),
	ROADBLOCKS VARCHAR(16777216),
	RAMP_UP_CURVE VARCHAR(50),
	DATA_SOURCES_COUNT NUMBER(38,0),
	INITIAL_RAW_VOLUME_TB FLOAT,
	FINAL_RAW_VOLUME_TB FLOAT,
	ANNUAL_GROWTH_RATE NUMBER(38,0),
	TOOLS VARCHAR(255),
	DATA_RETENTION_PERIOD NUMBER(38,0),
	DATA_SENSITIVITY VARCHAR(50),
	EXPECTED_WAREHOUSES NUMBER(38,0),
	TOTAL_USERS NUMBER(38,0),
	QUERY_COMPLEXITY VARCHAR(50),
	HAS_OTHER_WORKLOADS VARCHAR(10),
	OTHER_WORKLOAD_COUNT NUMBER(38,0),
	GEOGRAPHIC_DISTRIBUTION VARCHAR(255),
	HIGH_AVAILABILITY_REQUIREMENTS VARCHAR(50),
	DISASTER_RECOVERY_REQUIREMENTS VARCHAR(50),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (SIZING_ID)
);


-- Create a view for easy use case reporting
CREATE OR REPLACE VIEW SIZING_TOOL.CUSTOMER_SIZING.USE_CASE_SUMMARY AS
SELECT 
    uc.SIZING_ID,
    uc.USE_CASE_ID,
    uc.USE_CASE_NAME,
    uc.USE_CASE_DESCRIPTION,
    uc.BUSINESS_PRIORITY,
    uc.EXPECTED_TIMELINE,
    uc.BUSINESS_OWNER,
    uc.TECHNICAL_OWNER,
    uc.ESTIMATED_USERS,
    COUNT(DISTINCT aw.ANALYTICS_INDEX) as ANALYTICS_WORKLOADS_COUNT,
    COUNT(DISTINCT ds.SOURCE_INDEX) as DATA_SOURCES_COUNT,
    COUNT(DISTINCT ow.OTHER_INDEX) as OTHER_WORKLOADS_COUNT,
    COUNT(DISTINCT p.PIPELINE_INDEX) as PIPELINES_COUNT,
    SUM(ds.CURRENT_VOLUME_TB) as TOTAL_DATA_VOLUME_TB
FROM SIZING_TOOL.CUSTOMER_SIZING.USE_CASES uc
LEFT JOIN SIZING_TOOL.CUSTOMER_SIZING.ANALYTICS_WORKLOADS aw ON uc.USE_CASE_ID = aw.USE_CASE_ID
LEFT JOIN SIZING_TOOL.CUSTOMER_SIZING.DATA_SOURCES ds ON uc.USE_CASE_ID = ds.USE_CASE_ID
LEFT JOIN SIZING_TOOL.CUSTOMER_SIZING.OTHER_WORKLOADS ow ON uc.USE_CASE_ID = ow.USE_CASE_ID
LEFT JOIN SIZING_TOOL.CUSTOMER_SIZING.PIPELINES p ON uc.USE_CASE_ID = p.USE_CASE_ID
GROUP BY 
    uc.SIZING_ID, uc.USE_CASE_ID, uc.USE_CASE_NAME, uc.USE_CASE_DESCRIPTION,
    uc.BUSINESS_PRIORITY, uc.EXPECTED_TIMELINE, uc.BUSINESS_OWNER, 
    uc.TECHNICAL_OWNER, uc.ESTIMATED_USERS;
